[proxy_configuration]
HOST=brd.superproxy.io:22225
USERNAME=brd-customer-hl_93b5fa1a-zone-data_center
PASSWORD=ask3gh8zga95
USER_AGENT="Mozilla/5.0 (Windows NT 6.1; rv:84.0) Gecko/20100101 Firefox/84.0"
